set(Plugin-Name "M²aia Core Helper")
set(Plugin-Version "0.1")
set(Plugin-Vendor "M2")
set(Plugin-ContactAddress "https://m2aia.de")
set(Require-Plugin org.mitk.gui.qt.application org.mitk.gui.common org.mitk.gui.qt.datamanager)
set(Plugin-ActivationPolicy eager)
